### ISSUE TITLE
Cli reply text overlap

### ISSUE THREAD

**Issue by Caulm** [bsdayo/BingChat#26]
This occasionally occurs on window cmd, but it works good on powershell.
![image](https://github.com/bsdayo/BingChat/assets/40651411/5e826b62-6117-4d7d-9593-12e50e693239)
![image](https://github.com/bsdayo/BingChat/assets/40651411/f8730843-3f37-4434-b6e0-0dac10936fad)

**Comment by neon-sunset** [comment]
Yeah, this was fixed in https://github.com/bsdayo/BingChat/pull/25
Could you `dotnet tool update dotnet-bingchat` and try again?

**Comment by Caulm** [comment]
I just updated and tried again, but it still occurs... Also reproduced on powershell just now.
![image](https://github.com/bsdayo/BingChat/assets/40651411/9907edcd-08f4-4be1-928c-982bbfb8183e)

**Comment by neon-sunset** [comment]
Nevermind, I'm blind :D This is with bubble theme, the linked PR fixed the line one...
